version: '3.8'

services:
  memory-game:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: memory-multiplayer
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - memory-network

  # Optionnel : Ajouter Nginx comme reverse proxy
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - memory-game
    networks:
      - memory-network

networks:
  memory-network:
    driver: bridge

volumes:
  app-logs: