name: CI/CD Pipeline PoC

# Le pipeline se lance à chaque push sur la branche main
on:
  push:
    branches: [ "main" ]

jobs:
  # =========================================================
  # JOB UNIQUE : BUILD & DEPLOY SUR LE VPS (MINIKUBE)
  # =========================================================
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extraction du tag (Git SHA)
        id: vars
        run: echo "sha_short=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Build et déploiement via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # 1. Charger les configs
            export KUBECONFIG=/home/${{ secrets.VPS_USERNAME }}/.kube/config

            # 2. Mettre à jour le code source
            cd /home/hamidou/memory-game-ws
            git pull origin main

            # 3. Basculer vers le Docker daemon de Minikube
            eval $(minikube docker-env)

            # 4. Builder l'image directement dans Minikube
            IMAGE_TAG="memory-game:${{ steps.vars.outputs.sha_short }}"
            echo "Build de l'image: $IMAGE_TAG"
            docker build -t $IMAGE_TAG .

            # 5. Mettre à jour le deployment avec la nouvelle image
            kubectl set image deployment/memory-game-deployment \
              memory-game-container=$IMAGE_TAG \
              -n memory-game-dev

            # 6. Attendre que le rollout soit terminé
            kubectl rollout status deployment/memory-game-deployment \
              -n memory-game-dev --timeout=120s

            echo "Déploiement réussi avec le tag: ${{ steps.vars.outputs.sha_short }}"
